### ISSUE TITLE
Make 3.3 release

### ISSUE THREAD

**Issue by kjk** [sumatrapdfreader/sumatrapdf#1959]
This is a list of things to do / fix before making 3.3 release:
* [x] manual test of annotations to find / fix crashes and other issues
* [x] branch `rel3.3working`
* [x] announce in the forum for testing

Done:
* [x] update website with latest docs (annotations)
* [x] update release notes at https://www.notion.so/Version-3-3-823ab8f110ae448ba0b46c96f53da80c
* [x] write docs for annotations https://www.notion.so/Editing-annotations-15b0e4667f4f4825a4afe1bb10918914
* [x] https://github.com/sumatrapdfreader/sumatrapdf/issues/1991 improve confirmation dialog for unsaved annotations
* [x] https://github.com/sumatrapdfreader/sumatrapdf/issues/1977 Annotations don't show comment whilst adding
* [x] https://github.com/sumatrapdfreader/sumatrapdf/issues/1723 Show error when saving annotations fail; properly set incremental saving flag
* [x] https://github.com/sumatrapdfreader/sumatrapdf/issues/1974 Annotation odd color behaviour
* [x] add context menu `Select annotation` when cursor over annotation and edit annotation window is visible (replaces `Edit annotations` menu)
* [x] in annotations editor, add explicit button for saving to a new PDF instead of `ctrl` modifier
* [x] https://github.com/sumatrapdfreader/sumatrapdf/issues/1992
* [x] https://github.com/sumatrapdfreader/sumatrapdf/issues/1689
* [x] https://github.com/sumatrapdfreader/sumatrapdf/issues/1978
* [x] a way to change highlight color (via settings)
* [x] annotation color in settings is not respected
* [x] make use of Annotations.HighlightColor setting
* [x] decide on behavior for 'a' (no longer opens annotations editor; use shift + a to also open annotations editor)
* [x] a way to show that a window has unsaved annotations (https://github.com/sumatrapdfreader/sumatrapdf/issues/1973)
* [x] prompt to save unsaved annotations when closing window with Alt-F4 or by using close 'x' (https://github.com/sumatrapdfreader/sumatrapdf/issues/1962)
* [x] run stress test
* [x] website: https://www.sumatrapdfreader.org/settings/settings3.3.html doesn't work
* [x] fix website generation so that https://www.sumatrapdfreader.org/docs/Version-history correctly links to sub-pages
* [x] decide if should auto-expand toc tree when navigating within the doc, apparently in 3.1.2 it didn't and that happened in 3.2 (https://forum.sumatrapdfreader.org/t/auto-expansion-of-outline-bookmarks-in-v3-2/2787/2), https://github.com/sumatrapdfreader/sumatrapdf/issues/1937

**Comment by GitHubRulesOK** [comment]
OK the surprise=true is the implied "blocker" emphasis on "annotations" and 3.3 will be highly anticipated for that alone.

Moving annotations is highly/most desirable but MuPDF tends to "affect" those it substitutes such that custom inserts such as stamps can be degenerated. 
I have requested that there be a means (input exposure) for user to easily alter x,y dx,dy so they are only repositioned/scaled without altering content.

**Comment by GitHubRulesOK** [comment]
@kjk 
Maybe:
One of the most popular requests is:-
 Since hovering over tabs they change color (as does the exit cross) THUS ?? their target has a file name or is it just a position to close? IF its a traceable file name can it be shown in a tooltip?

**Comment by kjk** [comment]
I have to draw a line somewhere. If I keep adding things to 3.3 release, it'll never ship.

**Comment by GitHubRulesOK** [comment]
@kjk
I DO understand and your working as if to a deadline hence my Maybe:

**Comment by punk778** [comment]
For the last few months, I've been using the preview version and I don't have any noticeable problems with the average user. Tablet with Windows x32 and formats pdf and djvu in the main. Thank you)

**Comment by xsyt** [comment]
I am missing a keyboard function/shortcut for navigate through tabs like in a web browsers. Ctrl + PgUp/PgDown combination and Ctrl + 1..9 button.

**Comment by GitHubRulesOK** [comment]
@xsyt **OR OTHERS Landing here**. This is **not the thread for duplicating old requests** (I only added my reminder of the most common forum request), I suggest you search for open issue, read it and add your comment there then delete any post here.

**Comment by GitHubRulesOK** [comment]
@kjk 
**Just a thought**
Many apps do a RC1 release, could the 64bit daily's stay as pre-release whilst "pre-Release" now be compiled as if an RC# without any experimental features?

**Comment by GitHubRulesOK** [comment]
@kjk 
just tried to push latest version by open new window with large file over 32MB expecting problems but there were none ? Did you increase the pdf file locking limit or is it not relevant since SumatraPDF has full control ?
I will see if I can break that in another common scenario. Anyway the point of this comment was to add for 

**Documentation**
It is possible to open a second window to the same file **but beware** each window can have separate entries for annotation and must be **Either both added to that same source file OR each need to be saved** to separate files **you CANNOT save to new with both sets of annotation** ;-)
![image](https://user-images.githubusercontent.com/12754913/122660654-e7cb2e80-d17a-11eb-88a6-fba1343c7cda.png)

**Comment by GitHubRulesOK** [comment]
@kjk 
OK I am now more intrigued as to why I DO NOT have problems with large files Here I am combining Edge inking With SumatraPDF in a 37 MB file and was expecting issues with either saving to a locked file but had no such problem. So the question I have is **"Has the 32 MB locking been lifted?**" since that would be relative to LaTeX users using with progressive highlights.
![image](https://user-images.githubusercontent.com/12754913/122660925-4c878880-d17d-11eb-973b-851788fcc8aa.png)

**Comment by kjk** [comment]
The limit is still 32MB. Maybe mupdf doesn't lock the file?

**Comment by GitHubRulesOK** [comment]
@kjk 
**Documentation**
Impressed at the speed with showing latest updates, However I see the 

> "A (upper case), we'll create a highlight annotation from selection"

may imply selected content would be added like before / other apps.
So perhaps needs to mention 

> " You can use CTRL + V to paste the selection as a comment into the contents box."

**Comment by kjk** [comment]
I tweak the docs a bit at https://www.notion.so/Editing-annotations-15b0e4667f4f4825a4afe1bb10918914

Mentioned ctrl-v here: https://www.notion.so/Editing-annotations-15b0e4667f4f4825a4afe1bb10918914#a3d0c709ef404b9ea69a314e9089122a
